layout_spectrum: 0.9744681
typography_spectrum: 0.9319149
color:
  lightness: 0.7245091
  brandStrength: 0.4621426
  saturation: 0.06971128
  rhythmicContrast: 0.7579402
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Tesolikeapro
